server:
  servlet:
    context-path: /com.sh.orc

logging:
  config: classpath:logback.xml
  level:
    root: info

spring:
  application:
    name: plaform-ocr

tess4j:
  data-path: E:/tessdata-main

