server:
  servlet:
    context-path: /com.sh.orc

logging:
  config: classpath:logback-spring.xml
  level:
    root: info

spring:
  log-path: /logs/platform-ocr
  application:
    name: plaform-ocr

tess4j:
  data-path: E:/tessdata-main

